version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: mysql_db_nonn
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_nonnn:/var/lib/mysql  # เปลี่ยน volumes เป็น mysql_nonnn
    networks:
      - trytonon  # เปลี่ยน network เป็น trytonon

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_nonn
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "3000:80"
    depends_on:
      - db
    networks:
      - trytonon  # เปลี่ยน network เป็น trytonon

networks:
  trytonon:  # เปลี่ยน network เป็น trytonon
    driver: bridge

volumes:
  mysql_nonnn:  # เปลี่ยน volumes เป็น mysql_nonnn
    driver: local
